### ISSUE TITLE
Serde error on every video on rustytube.rs

### ISSUE THREAD

**Issue by Asdow** [opensourcecheemsburgers/RustyTube#29]
See screenshot, clicking any video from front page or through search results in these errors.
This on Firefox Nightly

![image](https://github.com/opensourcecheemsburgers/RustyTube/assets/20314541/d6b2b38f-81f0-4bf6-aeef-cc4c94632e11)

**Comment by opensourcecheemsburgers** [comment]
This is an [issue](https://github.com/iv-org/invidious/issues/4584) with all Invidious instances. 

For now, I recommend using FreeTube as it has a local parser. 

I'll look into implementing a local parser myself because Invidious has not been very reliable lately. For example, anotherInvidious [issue](https://github.com/iv-org/invidious/issues/4566) where comments do not load on any video.

On the plus side, SponsorBlock and more soon™.

**Comment by davehorner** [comment]
I'm getting the same thing on windows; at one time it was working for me.  I pulled the latest and tried today and all the videos say Serde Json Error.  Any suggestions on debugging are appreciated.

**Comment by opensourcecheemsburgers** [comment]
Fixed on the web version now :) 

I do not have time at  the moment to spin up VMs and compile it for Windows and Linux.

**Comment by davehorner** [comment]
i pulled latest and ran cargo tauri dev; the serde error is gone, the videos and text are all grey flashing boxes.  It then gives a "Network Error: TypeError: Failed to fetch"

I understand the time constraints.  Have a great night.

**Comment by davehorner** [comment]
Just to report back it did work with the server you mentioned.  I still see some serde errors but the program is usable.  Thank you.
